import {StyleSheet} from 'react-native';
import { Color } from '../../globals/GlobalStyles';

export const styles = StyleSheet.create({
        containerout: {
            flex: 1,
            backgroundColor: Color.white,
            // alignItems: 'center',
            width: '100%',
            // height: '100%',
        },
        container: {
            flex: 1,
            backgroundColor: Color.white,
            // alignItems: 'center',
            // justifyContent: 'center',
            width: '100%',
            // height: '100%',
        },
        head1: {
            fontSize: 40,
            textAlign: 'center',
            // fontWeight: '200',
            // marginVertical: 20,
            color: Color.red,
        },
        head2: {
            fontSize: 30,
            textAlign: 'center',
            fontWeight: '200',
            marginVertical: 20,
            elevation: 10,
            backgroundColor: Color.white,
            width: '90%',
            height: '50%',
            alignSelf: 'center',
            paddingVertical: '25%',
            borderRadius: 10,
        },
        cartcard: {
            flexDirection: 'row',
            backgroundColor: Color.white,
            marginVertical: 5,
            borderRadius: 10,
            width: '95%',
            alignSelf: 'center',
            elevation: 10,
            alignItems: 'center',
        },
        cartimg: {
            width: 150,
            height: 100,
            borderRadius: 10,
        },
        cartcardin: {
            flexDirection: 'column',
            margin: 5,
            width: '58%',
            alignItems: 'center',
            justifyContent: 'center',
            // backgroundColor: Color.red,
    
        },
        cardlist: {
            width: '100%',
        },
        cartout: {
            flex: 1,
            width: '100%',
        },
        btntxt: {
            backgroundColor: Color.red,
            color: Color.white,
            paddingHorizontal: 10,
            paddingVertical: 5,
            fontSize: 20,
            borderRadius: 10,
            width: '90%',
            textAlign: 'center',
    
        },
        btncont: {
            width: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 0,
            flexDirection: 'row',
            marginBottom: 80,
            borderTopColor: Color.black,
            borderTopWidth: 0.2,
        },
        bottomnav: {
            position: 'absolute',
            bottom: 0,
            width: '100%',
            backgroundColor: Color.white,
            zIndex: 20,
        },
        c1: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            width: '100%',
            backgroundColor: Color.white,
            borderRadius: 10,
            padding: 5,
        },
        txt1: {
            fontSize: 16,
            color: Color.red,
            width: '60%',
            fontWeight: 'bold',
        },
        txt2: {
            fontSize: 16,
            color: Color.black,
            fontWeight: 'bold',
        },
        c2: {
            backgroundColor: Color.red,
            borderRadius: 10,
            width: '100%',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 5,
            flexDirection: 'row',
        },
        txt3: {
            fontSize: 15,
            color: Color.white,
        },
        txt5: {
            fontSize: 20,
            color: Color.black,
            marginHorizontal: 5,
        },
        txt6: {
            fontSize: 25,
            color: Color.black,
            marginHorizontal: 5,
            fontWeight: 'bold',
        },
        c3: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        c4: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            width: 100,
            borderRadius: 10,
            borderColor: Color.red,
            borderWidth: 1,
            marginVertical: 10,
            padding: 5,
        },
        del: {
            color: Color.red,
        }
});
